### ISSUE TITLE
iOS - duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by cristianmgb** [syanbo/react-native-agora#91]
I follow the installation and configuration steps of the library, but when compiling it throws me the following error **75 duplicate symbols for architecture x86_64**

I use RN 0.59.8

**Comment by Matrixbirds** [comment]
@cristianmgb  You could try to using our [quick start](https://github.com/agoraio-community/agora-rn-quickstart). This error is issued by linker and this message indicates that your native compilation environment has many duplicate symbols which already linked, you could check did u have some any duplicate symbol link which probably already linked by Cocoapods. I think you could find more detail about this error in the compiler log file.

**Comment by cristianmgb** [comment]
I am following the next steps: `https://github.com/syanbo/react-native-agora/blob/master/docs/v2/ios.md`

**Comment by Matrixbirds** [comment]
Okay, If you r following this installation, that might be issued by **step 7**, You could remove this libRCTAgora.a from the link library and remove `RCTAgora.xcodeproj` from `Library` folder, because from 2.4.1 our npm wrapper already move RCTAgora compilation into Cocoapods. You can ignore the steps from **step 7**.

**Comment by cristianmgb** [comment]
Thank you

**Comment by Macrow** [comment]
能出一个新版的简要说明吗，配置了一天了，都一直在报错。
